Controllers/CursosPublicosController.cs
using Microsoft.AspNetCore.Mvc;

namespace LongDrink_aspnet.Controllers
{
    public class CursosPublicosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace LongDrink_aspnet.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/NosotrosController.cs
using Microsoft.AspNetCore.Mvc;

namespace LongDrink_aspnet.Controllers
{
    public class NosotrosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;

namespace LongDrink_aspnet.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Long Drink Bar - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LongDrink_aspnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/cocktail.png" width="32px" height="35px" style="filter: brightness(0) invert(1);"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Nosotros" asp-action="Index">Nosotros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="CursosPublicos" asp-action="Index">Cursos</a>
                        </li>
                    </ul>
                    <div class="col-md-3 text-end">
                        <a asp-area="" asp-controller="Register" asp-action="Index"><button type="button" class="btn btn-outline-danger me-2">Registrarse</button></a>
                        <a asp-area="" asp-controller="Login" asp-action="Index"><button type="button" class="btn btn-warning">Iniciar Sesión</button></a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Long Drink Bar - <a asp-area="" asp-controller="Nosotros" asp-action="Index">Nosotros</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>